#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/show_waybar &
$scripts/tools/dynamic &

# Update Mic Light
$scripts/update_mic_light &

# wallpaper
# $scripts/wall $config/wallpapers/cloud.png &

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Delayed wallpaper
sleep 1
$scripts/wall $config/wallpapers/cloud.png &
